Repository kescardoso/datasetbucket, pull requests merged in 2021-04, with the labels that each got.

#43 fixes
  generatePDF.py
  read_csv.py
  read_json.py
  runTerminalCommands.py
Labels: fixes

#44 Kaggle parse compile report fix
  read_json.py
  runTerminalCommands.py
Labels: fixes

#36 Staging
  .gitignore
  README.md
  app.py
  calculations.py
  data.csv
  data.json
  generatePDF.py
  read_csv.py
  read_json.py
  requirements.txt
  runTerminalCommands.py
  static/css/style.css
  static/images/android-chrome-192x192.png
  static/images/android-chrome-512x512.png
  static/images/apple-touch-icon.png
  static/images/favicon-16x16.png
  static/images/favicon-32x32.png
  static/images/favicon.ico
  static/js/script.js
  templates/about.html
  templates/add_dataset.html
  templates/analyse.html
  templates/base.html
  templates/datasets.html
  templates/edit_dataset.html
  user_uploads/GA_MachineLearning_B2C.pdf
  user_uploads/reinstalation.pdf
Labels: Development, documentation

#76 Pdf improvements
  calculations.py
  generatePDF.py
  read_csv.py
  read_json.py
Labels: Development

#85 added documentation
  CONTRIBUTION.md
  LIBRARIES.md
  README.md
Labels: documentation
